[defautl]
name = "VU1-Monitor"

[default.server]
hostname = "localhost"
port = 5340
logging_level = "DEBUG"
key = "cTpAWYuRpA2zx75Yh961Cg" # defult VU-Server key - please use your own key

[default.cpu]
name = "CPU"

[default.gpu]
name = "GPU"
backend = "nvidia"

[default.memory]
name = "MEMORY"

[default.network]
name = "NETWORK"
