[default.server]
hostname = "localhost"
port = 5340
logging_level = "INFO"

[default.cpu]
name = "CPU"

[default.gpu]
name = "GPU"

[default.memory]
name = "MEMORY"

[default.network]
name = "NETWORK"
